kubectl explain pod --recursive  >> Complete-pod.sh
kubectl explain deployment --recursive >> Complete-deployment.sh
kubectl explain replicaset --recursive >> Complete-replicaset.sh
kubectl explain replicationcontroller --recursive >> Complete-replicationcontroller.sh
kubectl explain service --recursive >> Complete-service.sh
kubectl explain daemonset --recursive >> Complete-daemonset.sh
kubectl explain namespace --recursive >> Complete-namespace.sh
kubectl explain persistentvolume --recursive >> Complete-persistentvolume.sh
kubectl explain persistentvolumeclaim --recursive >> Complete-persistentvolumeclaim.sh
kubectl explain job --recursive >> Complete-job.sh
kubectl explain Cronjob --recursive >> Complete-Cronjob.sh
